/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonah-hooper' at '2014/07/29 3:56 PM' with Gradle 2.0
 *
 * @author jonah-hooper, @date 2014/07/29 3:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
