import java.io.IOException;
import java.util.Random;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonah-hooper' at '2014/07/29 3:56 PM' with Gradle 2.0
 *
 * @author jonah-hooper, @date 2014/07/29 3:56 PM
 */
public class Program {
    public static void main(String[] args) throws IOException {
        Reader reader = new Reader();
        String initial = reader.readInitialState();
        System.out.println("log " + initial);
        GameController controller = new GameController();
        String[] nextStateRepresentation = reader.readNextGameState();
        while (nextStateRepresentation != null){
            GameState nextState = new GameState(nextStateRepresentation, null);
            controller.update(nextState);
            Direction nextMove = controller.move();
            System.out.println(Direction.asInt(nextMove));
            nextStateRepresentation = reader.readNextGameState();
        }
    }
}
