import java.io.IOException;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jonah-hooper' at '2014/07/29 3:56 PM' with Gradle 2.0
 *
 * @author jonah-hooper, @date 2014/07/29 3:56 PM
 */
public class Program {
    public static void main(String[] args) throws IOException {
        Reader reader = new Reader();
        String initial = reader.readInitialState();
        System.out.println("log " + initial);
        GameController controller = new GameController(new Basilisk());
        String[] nextStateRepresentation = reader.readNextGameState();
        double previousLength = Double.MAX_VALUE;
        double currentLength = 0.0;

        while (nextStateRepresentation != null){
            GameState nextState = new GameState(nextStateRepresentation, null);
            controller.update(nextState);
            Direction nextMove;
            currentLength = nextState.getOurSnake().getLength();

            // Log what our dead snake looked like
            if(currentLength < previousLength) {
                Logger.log("Snake death");
                Logger.log(nextStateRepresentation);
                Logger.log("===========");
            }

            try {
                nextMove = controller.move();
            } catch (Exception e) {
                Logger.log(e.getMessage());
                nextMove = nextState.getOurSnake().currentDirection();
            }

            System.out.println(Direction.asInt(nextMove));
            previousLength = currentLength;
            nextStateRepresentation = reader.readNextGameState();
        }
    }
}
